server:
  port: 8001
spring:
  application:
    name: payment-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true #可以不往eureka-server注册
    fetch-registry: true #应用是否去拉取服务列表到本地
    registry-fetch-interval-seconds: 10 #为了缓解服务列表的脏读问题