server:
  port: 80

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: false

ribbon:
  #返回结果耗时
  ReadTimeout: 5000
  #建立连接耗时
  ConnectionTimeout: 5000